"""Interactive setup wizard for airi."""

import sys
from pathlib import Path

from app.user_data import config_file, storage_dir, history_file, documents_dir

_BANNER = """
  Setup Wizard
  Configure airi
"""

_PROMPTS = [
    {
        "key": "OPENCODE_API_KEY",
        "label": "OpenCode API key",
        "required": True,
        "help": "Your API key for the OpenCode provider (opencode.ai)",
        "default": "",
        "secret": True,
    },
    {
        "key": "OPENCODE_MODEL",
        "label": "OpenCode model",
        "required": False,
        "help": "Model to use (e.g. kimi-k2.6, qwen3.6-plus, glm-5)",
        "default": "kimi-k2.6",
        "secret": False,
    },
    {
        "key": "LANG_SEARCH_API",
        "label": "Lang Search API key",
        "required": False,
        "help": "API key for web search (leave empty to disable web search)",
        "default": "",
        "secret": True,
    },
    {
        "key": "OLLAMA_URL",
        "label": "Ollama URL",
        "required": False,
        "help": "URL for local Ollama embeddings server",
        "default": "http://localhost:11434",
        "secret": False,
    },
    {
        "key": "SMTP_HOST",
        "label": "SMTP host",
        "required": False,
        "help": "SMTP server for sending emails (leave empty to disable)",
        "default": "",
        "secret": False,
    },
    {
        "key": "SMTP_PORT",
        "label": "SMTP port",
        "required": False,
        "help": "SMTP port (587 for STARTTLS, 465 for SSL)",
        "default": "587",
        "secret": False,
    },
    {
        "key": "SMTP_USERNAME",
        "label": "SMTP username",
        "required": False,
        "help": "SMTP login username",
        "default": "",
        "secret": False,
    },
    {
        "key": "SMTP_PASSWORD",
        "label": "SMTP password",
        "required": False,
        "help": "SMTP login password",
        "default": "",
        "secret": True,
    },
    {
        "key": "SMTP_SENDER",
        "label": "SMTP sender email",
        "required": False,
        "help": "Email address to send from",
        "default": "",
        "secret": False,
    },
]


def _mask(secret: str) -> str:
    if not secret:
        return "(not set)"
    return "*" * (len(secret) - 4) + secret[-4:]


def _read_existing() -> dict[str, str]:
    """Parse existing .env file into a dict."""
    path = config_file()
    if not path.is_file():
        return {}
    result = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    return result


def _prompt_value(label: str, default: str, secret: bool, help_text: str) -> str:
    """Prompt the user for a value, showing the default and help text."""
    print(f"\n  {label}")
    print(f"  {_color_dim(help_text)}")
    if default:
        print(f"  {_color_dim(f'Default: {default}')}")
    try:
        value = input(f"  > ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        return default
    if not value:
        return default
    return value


def _color_dim(text: str) -> str:
    try:
        return f"\033[2m{text}\033[0m"
    except Exception:
        return text


def _color_green(text: str) -> str:
    try:
        return f"\033[32m{text}\033[0m"
    except Exception:
        return text


def _color_yellow(text: str) -> str:
    try:
        return f"\033[33m{text}\033[0m"
    except Exception:
        return text


def _color_red(text: str) -> str:
    try:
        return f"\033[31m{text}\033[0m"
    except Exception:
        return text


def _color_bold(text: str) -> str:
    try:
        return f"\033[1m{text}\033[0m"
    except Exception:
        return text


def _write_env(values: dict[str, str]) -> None:
    """Write key=value pairs to the user's .env config file."""
    path = config_file()
    lines = [
        "# airi configuration",
        "# Generated by /setup wizard",
        f"# User data directory: {storage_dir()}",
        "",
    ]
    for prompt in _PROMPTS:
        key = prompt["key"]
        value = values.get(key, "")
        if value:
            lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _test_api_key(api_key: str, model: str) -> tuple[bool, str]:
    """Make a small test call to verify the API key works."""
    try:
        from app.chat_opencode import ChatOpenCode

        llm = ChatOpenCode(
            api_key=api_key,
            model_name=model,
            temperature=0,
            max_tokens=10,
        )
        response = llm.invoke("Say OK")
        return True, response.content.strip()[:50]
    except Exception as exc:
        return False, str(exc)[:150]


def _test_ollama(url: str) -> tuple[bool, str]:
    """Check if Ollama is reachable for embeddings."""
    try:
        import httpx

        resp = httpx.get(f"{url}/api/tags", timeout=5)
        resp.raise_for_status()
        models = resp.json().get("models", [])
        model_names = [m.get("name", "") for m in models]
        has_embedding = any("embed" in m for m in model_names)
        if model_names:
            return True, f"Found models: {', '.join(model_names[:3])}"
        return True, "Connected (no models pulled yet)"
    except Exception as exc:
        return False, str(exc)[:100]


def run_setup() -> None:
    """Run the interactive setup wizard."""
    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8")

    print(_color_bold("─" * 50))
    print(_color_bold("  airi — Setup Wizard"))
    print(_color_bold("─" * 50))
    print()
    print(f"  {_color_dim('User data directory:')} {_color_bold(str(storage_dir()))}")

    existing = _read_existing()
    if existing:
        print(f"\n  {_color_dim('Existing configuration found. Press Enter to keep current values.')}")
        print(f"  {_color_dim('Current values:')}")
        for prompt in _PROMPTS:
            key = prompt["key"]
            value = existing.get(key, "")
            display = _mask(value) if prompt["secret"] else (value or "(not set)")
            print(f"    {prompt['label']}: {display}")

    print(f"\n  {_color_dim('Fill in the settings below (required fields marked with *):')}")

    values = {}
    missing_required = []

    for prompt in _PROMPTS:
        key = prompt["key"]
        existing_val = existing.get(key, "")
        default = existing_val if existing_val else prompt["default"]
        value = _prompt_value(
            label=f"{prompt['label']}{' *' if prompt['required'] else ''}",
            default=default,
            secret=prompt["secret"],
            help_text=prompt["help"],
        )
        values[key] = value

        if prompt["required"] and not value:
            missing_required.append(prompt["label"])

    if missing_required:
        print(f"\n  {_color_red('Missing required settings:')} {', '.join(missing_required)}")
        print(f"  {_color_dim('You can set them later by running /setup again.')}")
        return

    # Test API key if provided
    api_key = values.get("OPENCODE_API_KEY", "")
    model = values.get("OPENCODE_MODEL", "kimi-k2.6")
    if api_key:
        print(f"\n  {_color_dim('Testing API key...')}")
        ok, msg = _test_api_key(api_key, model)
        if ok:
            print(f"  {_color_green('API key OK.')} {_color_dim(f'Response: {msg}')}")
        else:
            print(f"  {_color_red('API key test failed:')} {msg}")
            try:
                retry = input(f"  {_color_yellow('Continue anyway? (y/n): ')}").strip().lower()
            except (EOFError, KeyboardInterrupt):
                retry = "y"
            if retry != "y":
                print(f"  {_color_dim('Setup cancelled.')}")
                return

    # Test Ollama if URL provided
    ollama_url = values.get("OLLAMA_URL", "")
    if ollama_url:
        print(f"\n  {_color_dim('Testing Ollama connection...')}")
        ok, msg = _test_ollama(ollama_url)
        if ok:
            print(f"  {_color_green('Ollama OK.')} {_color_dim(msg)}")
        else:
            print(f"  {_color_yellow('Ollama not reachable:')} {_color_dim(msg)}")

    # Save configuration
    _write_env(values)
    print(f"\n  {_color_green('Configuration saved to:')} {_color_bold(str(config_file()))}")

    # Show summary
    print(f"\n  {_color_bold('Summary:')}")
    print(f"    {_color_dim('Config file:')} {config_file()}")
    print(f"    {_color_dim('Storage:')} {storage_dir()}")
    print(f"    {_color_dim('Documents:')} {documents_dir()}")
    print(f"    {_color_dim('History:')} {history_file()}")
    print(f"\n  {_color_green('Setup complete!')} {_color_dim('Run the assistant to start chatting.')}")
